module tb_top (
  input  logic        clk,
  input  logic        rst_n,
  // TX (noc_in_*) � master drives writes, reads local CSR/buffer
  input  logic        awvalid,
  output logic        awready,
  input  logic [31:0] awaddr,
  input  logic [7:0]  awlen,
  input  logic [2:0]  awsize,
  input  logic [1:0]  awburst,
  input  logic        awid,
  input  logic        wvalid,
  output logic        wready,
  input  logic [31:0] wdata,
  input  logic [3:0]  wstrb,
  input  logic        wlast,
  input  logic        bready,
  output logic        bvalid,
  output logic [1:0]  bresp,
  output logic        bid,
  input  logic        arvalid,
  output logic        arready,
  input  logic [31:0] araddr,
  input  logic [7:0]  arlen,
  input  logic [2:0]  arsize,
  input  logic [1:0]  arburst,
  input  logic        arid,
  input  logic        rready,
  output logic        rvalid,
  output logic [31:0] rdata,
  output logic [1:0]  rresp,
  output logic        rlast,
  output logic        rid,
  // RX (noc_out_*) � slave BFM drives responses to router [1][1]
  output logic        rx_awready,
  output logic        rx_awvalid,
  output logic [31:0] rx_awaddr,
  output logic [7:0]  rx_awlen,
  output logic [2:0]  rx_awsize,
  output logic [1:0]  rx_awburst,
  output logic        rx_awid,
  output logic        rx_wready,
  output logic        rx_wvalid,
  output logic [31:0] rx_wdata,
  output logic [3:0]  rx_wstrb,
  output logic        rx_wlast,
  output logic        rx_bready,
  output logic        rx_bvalid,
  output logic [1:0]  rx_bresp,
  output logic        rx_bid,
  output logic        rx_arready,
  output logic        rx_arvalid,
  output logic [31:0] rx_araddr,
  output logic [7:0]  rx_arlen,
  output logic [2:0]  rx_arsize,
  output logic [1:0]  rx_arburst,
  output logic        rx_arid,
  output logic        rx_rready,
  output logic        rx_rvalid,
  output logic [31:0] rx_rdata,
  output logic [1:0]  rx_rresp,
  output logic        rx_rlast,
  output logic        rx_rid
);
  import ravenoc_pkg::*;
  import amba_axi_pkg::*;

  ravenoc_wrapper #(.DEBUG(0)) dut (
    .clk_axi(clk), .clk_noc(clk),
    .arst_axi(~rst_n), .arst_noc(~rst_n),
    .bypass_cdc(1'b1),
    .act_in(1'b1),  .axi_sel_in('0),
    .act_out(1'b1), .axi_sel_out(2'd3),
    // TX noc_in_*
    .noc_in_awid(awid),       .noc_in_awaddr(awaddr),
    .noc_in_awlen(awlen),     .noc_in_awsize(awsize),
    .noc_in_awburst(awburst), .noc_in_awlock('0),
    .noc_in_awcache('0),      .noc_in_awprot('0),
    .noc_in_awqos('0),        .noc_in_awregion('0),
    .noc_in_awuser('0),       .noc_in_awvalid(awvalid),
    .noc_in_awready(awready),
    .noc_in_wdata(wdata),     .noc_in_wstrb(wstrb),
    .noc_in_wlast(wlast),     .noc_in_wuser('0),
    .noc_in_wvalid(wvalid),   .noc_in_wready(wready),
    .noc_in_bready(bready),   .noc_in_bid(bid),
    .noc_in_bresp(bresp),     .noc_in_buser(),
    .noc_in_bvalid(bvalid),
    .noc_in_arid(arid),       .noc_in_araddr(araddr),
    .noc_in_arlen(arlen),     .noc_in_arsize(arsize),
    .noc_in_arburst(arburst), .noc_in_arlock('0),
    .noc_in_arcache('0),      .noc_in_arprot('0),
    .noc_in_arqos('0),        .noc_in_arregion('0),
    .noc_in_aruser('0),       .noc_in_arvalid(arvalid),
    .noc_in_arready(arready), .noc_in_rready(rready),
    .noc_in_rid(rid),         .noc_in_rdata(rdata),
    .noc_in_rresp(rresp),     .noc_in_rlast(rlast),
    .noc_in_ruser(),          .noc_in_rvalid(rvalid),
    // RX noc_out_*
    .noc_out_awid(rx_awid),       .noc_out_awaddr(rx_awaddr),
    .noc_out_awlen(rx_awlen),     .noc_out_awsize(rx_awsize),
    .noc_out_awburst(rx_awburst), .noc_out_awlock('0),
    .noc_out_awcache('0),         .noc_out_awprot('0),
    .noc_out_awqos('0),           .noc_out_awregion('0),
    .noc_out_awuser('0),          .noc_out_awvalid(rx_awvalid),
    .noc_out_awready(rx_awready),
    .noc_out_wdata(rx_wdata),     .noc_out_wstrb(rx_wstrb),
    .noc_out_wlast(rx_wlast),     .noc_out_wuser('0),
    .noc_out_wvalid(rx_wvalid),   .noc_out_wready(rx_wready),
    .noc_out_bready(rx_bready),   .noc_out_bid(rx_bid),
    .noc_out_bresp(rx_bresp),     .noc_out_buser(),
    .noc_out_bvalid(rx_bvalid),
    .noc_out_arid(rx_arid),       .noc_out_araddr(rx_araddr),
    .noc_out_arlen(rx_arlen),     .noc_out_arsize(rx_arsize),
    .noc_out_arburst(rx_arburst), .noc_out_arlock('0),
    .noc_out_arcache('0),         .noc_out_arprot('0),
    .noc_out_arqos('0),           .noc_out_arregion('0),
    .noc_out_aruser('0),          .noc_out_arvalid(rx_arvalid),
    .noc_out_arready(rx_arready), .noc_out_rready(rx_rready),
    .noc_out_rid(rx_rid),         .noc_out_rdata(rx_rdata),
    .noc_out_rresp(rx_rresp),     .noc_out_rlast(rx_rlast),
    .noc_out_ruser(),             .noc_out_rvalid(rx_rvalid)
  );

endmodule
